# _config.yml

# Site settings
title: "Insert Title Here"  # Replace with your site title
description: "Replace with your site description or tagline."
url: "https://example.com"        # Your production URL
baseurl: ""                    # e.g. "/blog" if served from a subpath

# Theming
theme:
  font:
    family: "Montserrat"
    weights: ["400", "600", "700"]

  border_radius: "0.5rem"

  colors:
    # backgrounds
    background:      "#ffffff"
    background_alt:  "#f9f9f9"
    surface:         "#eeeeee"

    # primary / secondary
    primary:         "#777777"
    primary_light:   "#888888"
    primary_dark:    "#666666"
    secondary:       "#aaaaaa"
    secondary_light: "#bbbbbb"
    secondary_dark:  "#999999"

    # text
    text:            "#333333"
    text_light:      "#666666"

    # accents & states
    accent:          "#dddddd"
    accent_dark:     "#cccccc"
    error:           "#ff0000"

# Site data
hero:
  description: "Replace me with your hero section headline or tagline."
  image: "/assets/hero.webp"

cta:
  title: "Call To Action Title Here"
  text: "Replace me with a short call-to-action message."
  button: "Button Text Here"

quote:
  submission_url: "https://shadow-seagull-4892.twil.io/submit_quote_request"

# Contact info
phone:
  ie64: "+16473636683"          # International dialing number, no spaces
  display: "(123) 456-7890"   # Formatted display phone number
  twilio_account_sid: "AC2d402e54f448be3bafcc2cc1df1ddf4f"
email: "contact@example.com"
contact:
  title: "Contact Our Branch"
address:
  - "123 Example Street"
  - "Suite 100"
  - "City, State ZIP"
hours:
  - "Mon–Fri: 9 AM – 6 PM"
  - "Sat: 10 AM – 4 PM"
  - "Sun: Closed"

# Navigation links
nav_links:
  - title: "Services"
    url: "#services"
  - title: "Locations"
    url: "#locations"
  - title: "Moving Tips"
    url: "#moving-tips"
  - title: "About Us"
    url: "#about"

# Footer lists
services:
  - name: "Residential Moves"
  - name: "Commercial Moves"
  - name: "Packing Services"
  - name: "Storage Solutions"

locations:
  - name: "Location A"
  - name: "Location B"
  - name: "Location C"
  - name: "Location D"

# Testimonials for carousel
testimonials:
  - text: "Replace with your first testimonial text."
    author: "— Jane Doe"
    location: "City Name"
    rating: 5
  - text: "Replace with your second testimonial."
    author: "— John Smith"
    location: "Another City"
    rating: 4.5
  - text: "Replace with your third testimonial."
    author: "— Alice Johnson"
    location: "Sample City"
    rating: 4
